on : [push]
jobs:
    build:
        runs-on: ubuntu-latest
        # ...
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2.3.1
              with:
                url: http://65.1.112.91:8200
                method: approle
                roleId: ${{ secrets.roleId }}
                secretId: ${{ secrets.secretId }}
                secrets: |
                    secret/jenkins/github private-token | PRIVATE_KEY ;
                    secret/jenkins/github public-token | PUBLIC_KEY ;
