on : [push]
jobs:
    build:
        runs-on: ubuntu-latest
        # ...
        steps:
            # ...
            - name: Import Secrets
              uses: hashicorp/vault-action@v2.3.1
              with:
                url: http://13.233.152.68:8200
                method: approle
                roleId: d6f0a26f-cde0-14a8-aa24-0eb2ca174d97
                secretId: f8e9f026-43de-3f34-d4d4-5ceb3e19a1d9
                secrets: |
                    secret/jenkins/github private-token | PRIVATE_KEY ;
                    secret/jenkins/github public-token | PUBLIC_KEY ;
